[tool]
[tool.poetry]
authors = ["Quentin Mennecart<quentin.mennecart@gmail.com>"]
description = "Time series visualizer - Freecodecamp Python certification"
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
pandas = "*"
python = "^3.8"
seaborn = "*"
